name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: true
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: true
jobs:
  create-report:
    permissions:
      contents: read
      issues: write
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: "terraform-kt"
          GITHUB_OWNER_FOR_ISSUE: "Kasunmadura"
          GITHUB_OWNERS_REPOS: "Kasunmadura/terraform-kt"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
